# Generated by Django 4.0.4 on 2022-06-07 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('period', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], verbose_name='교시')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('place', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ToolBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booker', models.CharField(max_length=10)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.period')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.tool')),
            ],
        ),
        migrations.CreateModel(
            name='LeftTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left', models.PositiveSmallIntegerField()),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.period')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.tool')),
            ],
        ),
    ]
