# Generated by Django 4.0.4 on 2022-07-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolbooking',
            name='password',
            field=models.CharField(default='0000', max_length=4),
        ),
    ]
